2025-01-19 20:36:15 - main_4 - DEBUG - Login Request Received
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Request Headers: Host: localhost:5000
Connection: keep-alive
Content-Length: 50
Sec-Ch-Ua-Platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Sec-Ch-Ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
Content-Type: application/json
Sec-Ch-Ua-Mobile: ?0
Origin: http://localhost:5173
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:5173/
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Request Data: {'email': 'kali@kali.com', 'password': 'password123'}
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Attempting to fetch user: kali@kali.com
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - User found: (1, 'kali@kali.com', 'password123', 1)
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Stored password for kali@kali.com: password123
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Password Verification Initiated
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Provided Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Stored Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Stored password encoded successfully
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - DEBUG - Provided password encoded successfully
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - ERROR - Bcrypt Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - ERROR - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - CRITICAL - Comprehensive Password Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - CRITICAL - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - ERROR - Password verification error: Invalid salt
Exception Traceback:
None
2025-01-19 20:36:15 - main_4 - ERROR - Full traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 183, in login
    if verify_password(password, stored_password):
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Login Request Received
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Request Headers: Host: localhost:5000
Connection: keep-alive
Content-Length: 50
Sec-Ch-Ua-Platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Sec-Ch-Ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
Content-Type: application/json
Sec-Ch-Ua-Mobile: ?0
Origin: http://localhost:5173
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:5173/
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Request Data: {'email': 'kali@kali.com', 'password': 'password123'}
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Attempting to fetch user: kali@kali.com
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - User found: (1, 'kali@kali.com', 'password123', 1)
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Stored password for kali@kali.com: password123
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Password Verification Initiated
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Provided Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Stored Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Stored password encoded successfully
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - DEBUG - Provided password encoded successfully
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - ERROR - Bcrypt Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - ERROR - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - CRITICAL - Comprehensive Password Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - CRITICAL - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - ERROR - Password verification error: Invalid salt
Exception Traceback:
None
2025-01-19 20:38:28 - main_4 - ERROR - Full traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 183, in login
    if verify_password(password, stored_password):
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Login Request Received
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Request Headers: Host: localhost:5000
Connection: keep-alive
Content-Length: 50
Sec-Ch-Ua-Platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Sec-Ch-Ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
Content-Type: application/json
Sec-Ch-Ua-Mobile: ?0
Origin: http://localhost:5173
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:5173/
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Request Data: {'email': 'kali@kali.com', 'password': 'password123'}
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Attempting to fetch user: kali@kali.com
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - User found: (1, 'kali@kali.com', 'password123', 1)
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Stored password for kali@kali.com: password123
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Password Verification Initiated
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Provided Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Stored Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Stored password encoded successfully
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - DEBUG - Provided password encoded successfully
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - ERROR - Bcrypt Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - ERROR - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - CRITICAL - Comprehensive Password Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - CRITICAL - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - ERROR - Password verification error: Invalid salt
Exception Traceback:
None
2025-01-19 20:38:44 - main_4 - ERROR - Full traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 183, in login
    if verify_password(password, stored_password):
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Login Request Received
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Request Headers: Host: localhost:5000
Connection: keep-alive
Content-Length: 50
Sec-Ch-Ua-Platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Sec-Ch-Ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
Content-Type: application/json
Sec-Ch-Ua-Mobile: ?0
Origin: http://localhost:5173
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:5173/
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Request Data: {'email': 'kali@kali.com', 'password': 'password123'}
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Attempting to fetch user: kali@kali.com
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - User found: (1, 'kali@kali.com', 'password123', 1)
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Stored password for kali@kali.com: password123
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Password Verification Initiated
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Provided Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Stored Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Stored password encoded successfully
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - DEBUG - Provided password encoded successfully
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - ERROR - Bcrypt Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - ERROR - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - CRITICAL - Comprehensive Password Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - CRITICAL - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - ERROR - Password verification error: Invalid salt
Exception Traceback:
None
2025-01-19 20:39:15 - main_4 - ERROR - Full traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 183, in login
    if verify_password(password, stored_password):
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Login Request Received
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Request Headers: Host: localhost:5000
Connection: keep-alive
Content-Length: 50
Sec-Ch-Ua-Platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Sec-Ch-Ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
Content-Type: application/json
Sec-Ch-Ua-Mobile: ?0
Origin: http://localhost:5173
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:5173/
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Request Data: {'email': 'kali@kali.com', 'password': 'password123'}
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Attempting to fetch user: kali@kali.com
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - User found: (1, 'kali@kali.com', 'password123', 1)
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Stored password for kali@kali.com: password123
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Password Verification Initiated
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Provided Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Stored Password Type: <class 'str'>
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Stored password encoded successfully
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - DEBUG - Provided password encoded successfully
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - ERROR - Bcrypt Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - ERROR - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - CRITICAL - Comprehensive Password Verification Error: Invalid salt
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - CRITICAL - Full Traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - ERROR - Password verification error: Invalid salt
Exception Traceback:
None
2025-01-19 20:50:15 - main_4 - ERROR - Full traceback: Traceback (most recent call last):
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 183, in login
    if verify_password(password, stored_password):
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cazzano/DB/Emergency/Coding/Github_Projects/J.I.R.C/cms/beta/backend/main_4.py", line 95, in verify_password
    verification_result = bcrypt.checkpw(provided_password, stored_password)
ValueError: Invalid salt

Exception Traceback:
None
